name: Run Tests

on: [push, pull_request]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps: 

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Checkout repository
      uses: actions/checkout@v2
       
    # - name: Run tests
    #   env:
    #     AZURE_OPENAI_KEY: 
    #   run: pytest tests/tests_unit.py
    
    - name: azure acr login
      run: |
        az acr login --name chatbotjim

    - name: build and push images
      run: |
        docker build --build-arg AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }} -t chatbotback:latest -f Dockerfile .
        docker build -t chatbotfront:latest -f front/Dockerfile front/
        docker tag chatbotback:latest chatbotjim.azurecr.io/chatbotback:latest
        docker tag chatbotfront:latest chatbotjim.azurecr.io/chatbotfront:latest
        docker push chatbotjim.azurecr.io/chatbotback:latest
        docker push chatbotjim.azurecr.io/chatbotfront:latest
    
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
          find: "password.registry"
          replace: "${{ secrets.REGISTRY_PASSWORD }}"
          regex: false
          include: 'deploy-aci.yaml'
    
          
    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az container delete --name chatbotjim --resource-group ajax_jim --yes
          az container create --resource-group ajax_jim --file deploy-aci.yaml