name: Deploy to Azure Container Instances

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker images
      run: |
        docker build -t chatbotjim.azurecr.io/chatbotback:latest .
        docker build -t chatbotjim.azurecr.io/chatbotfront:latest front/
        echo ${{ secrets.REGISTRY_PASSWORD }} | docker login chatbotjim.azurecr.io -u chatbotjim --password-stdin
        docker push chatbotjim.azurecr.io/chatbotback:latest
        docker push chatbotjim.azurecr.io/chatbotfront:latest

    - name: Deploy to Azure Container Instances
      run: |
        az container create \
          --resource-group your-resource-group-name \
          --name chatbotjim \
          --image chatbotjim.azurecr.io/chatbotback:latest \
          --cpu 1 \
          --memory 1.5 \
          --ports 8008 \
          --dns-name-label chatbotjim \
          --ip-address Public

        az container create \
          --resource-group your-resource-group-name \
          --name chatbotjim-front \
          --image chatbotjim.azurecr.io/chatbotfront:latest \
          --cpu 1 \
          --memory 1.5 \
          --ports 8011 \
          --dns-name-label chatbotjim-front \
          --ip-address Public
